### ISSUE TITLE
CF local design 

### ISSUE THREAD

**Issue by JenneyJ** [cloudfoundry-incubator/cflocal#8]
HI,

This is more of question :) 
I try it and it works great!
How does it works from design aspect's?
 I see that you are using Docker but what is actually happening under the hood when I stage & and run app ? (using local) 

in addition, 
let's say I've project like following 

```
myApp
  web
    index.html
    test.html
```
and I run the application for first time  which works and I see the html content in the browser ,
Now I change the index.html content and I want to see the changes in the browser , there is a way to see those changes **without** the need to stage the app , just to run it ...? 
something like when you use docker to run locally with volume mapping ...

Thanks!

**Comment by sclevine** [comment]
Hi @JenneyJ,

CF Local uses two Docker images:
1. The `cloudfoundry/cflinuxfs2` image from Docker Hub, which is a Docker image version of the official cflinuxfs2 app container rootfs used in CF. This image is used for `cf local run` and `cf local export`.
2. A separate image tagged as `cflocal`, which uses `cloudfoundry/cflinuxfs2` as a base image and includes the buildpack lifecycle components from Diego as well as packages of the online buildpacks from the official CF buildpack repos. This image is used for `cf local stage`.

Each time `cf local` is run, `cloudfoundry/cflinuxfs2` is updated to the latest version, and `cflocal` is re-built (if necessary).

To implement service forwarding, separate containers are used to create a network namespace, run the local app, and establish SSH tunnels to the remote app.

To sync local directories to the app directory, a combination of volume mounts and rsync is used.

The feature you're asking about can be accomplished with `cf local run <app-name> -d <local-dir>`. The `-r` option uses rsync to prevent modifications to the local directory and speed up volume mounted apps on platforms with slow volume mounts. The `-w` option causes the app to restart when changes are made to the local directory.

The caveat is that some buildpacks make significant changes to the app directory. To work around this, the staged app is copied into `<local-dir>` if `<local-dir>` is empty. Alternatively, you can stage a local directory with `cf local stage <app-name> -d <local-dir> -r`, and then use that directory with `cf local run`. The buildpacks team is working on modifying the buildpack contract so that changes to the app directory aren't necessary when iterating on apps.

Hope this is help!

**Comment by JenneyJ** [comment]
Thank you very much! this is very helpful , great job!

**Comment by JenneyJ** [comment]
HI Again :),

I've tested the re-sync and I got error when trying to run the app .
the error is: `bash: npm: command not found     `
e.g. 

This is my App

```
myApp
  web
    index.html
    test.html
```
What I tried is to run the following: (`pwd` - in the command line is my project root) 

`cf local run app1  -d web/ -w`

I tried to sync the changes in the web folder that if I do any change in the index html by refreshing the browser it will detected ...

Any idea what could be missing ? 

when Im just using `cf local run app1` it works without any error

Thanks!

**Comment by sclevine** [comment]
Can you provide a sample app, as well as the command you're using to stage the app?

**Comment by JenneyJ** [comment]
Hi,

I was able to make it work, thank you!

Thanks,
Jenney

**Comment by sclevine** [comment]
Awesome!
